### PR TITLE
fix: edge case where empty value overwrite existing value

### PR DESCRIPTION
**Pull request by tungfinblox**
# Reason for This PR

We found another edge case where `http` package can potentially wrongly overwrite data

Let's say that we have a form like this:

```
form := url.Values{}
form.Add("name[]", "name1")
form.Add("name[]", "name2")
form.Add("name[]", "name3")
form.Add("name", "")
```

Because iterating over map in Go is random so this case might not happen all the time. But when it happens,
data under `name` key will be empty string which in our case removes all the relationships in Laravel backpack.

I also refactor the test cases to be shorter and with better description.

## Description of Changes

Fix one more edge case where empty value can potentially overwrite existing value.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by rustatian** [comment]
Hey @tungfinblox 👋🏻 

Thanks again for the PR 👍🏻 

I think the `mount` function gets bigger and bigger with the complicated logic w/o proper comments. There are a lot of vars like `isOldDataEmpty`, `dataTreeOK`, which indicate a badly designed algo.

The algorithm should be completely redesigned with these new cases. I'll need to think about how to design it better.

Could you please, add comments for the users, like:

```go
/*
Here we're doing the following ...
1. ...
2. ...
*/
	_, dataTreeOK := dt[i[0]].(dataTree)
	if !dataTreeOK {
/*
Checking the ...
*/
```

**Comment by tungfinblox** [comment]
> Hey @tungfinblox 👋🏻
> 
> Thanks again for the PR 👍🏻
> 
> I think the `mount` function gets bigger and bigger with the complicated logic w/o proper comments. There are a lot of vars like `isOldDataEmpty`, `dataTreeOK`, which indicate a badly designed algo.
> 
> The algorithm should be completely redesigned with these new cases. I'll need to think about how to design it better. I think there are no problems from your side, but initially, I not properly designed it.
> 
> Could you please, add comments for the users, like:
> 
> ```go
> /*
> Here we're doing the following ...
> 1. ...
> 2. ...
> */
> 	_, dataTreeOK := dt[i[0]].(dataTree)
> 	if !dataTreeOK {
> /*
> Checking the ...
> */
> ```

Hi @rustatian 

I understand. Lemme think of a way to make it easier to understand.

**Comment by rustatian** [comment]
Yeah, so, for me, I understand what's happening there. But for other contributors, that might be problematic to figure out.

**Comment by tungfinblox** [comment]
Hey @rustatian 

Sorry for closing this.I will prepare another PR when the code is ready 👍

**Comment by rustatian** [comment]
Hey @tungfinblox 👋🏻 

Sure, no problem.

**Pull request closed without merging**
